/** Generated by english-annotation-buster, Powered by Google Translate.**/
/**
 * Root package for Spring's serializer interfaces and implementations.
 * Provides an abstraction over various serialization techniques.
 * Includes exceptions for serialization and deserialization failures.
 */
/**
 * Spring的序列化程序接口和实现的根包。 
 * 提供各种序列化技术的抽象。 
 * 包括序列化和反序列化失败的异常。 
 * 
 */
@NonNullApi
@NonNullFields
package org.springframework.core.serializer;

import org.springframework.lang.NonNullApi;
import org.springframework.lang.NonNullFields;
