/** Generated by english-annotation-buster, Powered by Google Translate.**/
/*
 * Copyright 2002-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * 版权所有2002-2019的原始作者或作者。 
 * 根据Apache许可证2.0版（"许可证"）获得许可； 
 * 除非遵守许可，否则不得使用此文件。 
 * 您可以在https://www.apache.org/licenses/LICENSE-2.0上获得许可的副本。 
 * 除非适用法律要求或以书面形式同意，否则根据"许可"分发的软件将按"现状"分发，没有任何明示或暗示的保证或条件。 
 * 有关许可下特定的语言管理权限和限制，请参阅许可。 
 * 
 */

package org.springframework.test.context.event;

import org.springframework.context.ApplicationEvent;
import org.springframework.test.context.TestContext;

/**
 * Base class for events published by the {@link EventPublishingTestExecutionListener}.
 *
 * @author Frank Scheffler
 * @author Sam Brannen
 * @since 5.2
 */
/**
 * 由{@link  EventPublishingTestExecutionListener}发布的事件的基类。 
 *  @author 弗兰克·谢弗勒（Frank Scheffler）@author  Sam Brannen @5.2起
 */
@SuppressWarnings("serial")
public abstract class TestContextEvent extends ApplicationEvent {

	/**
	 * Create a new {@code TestContextEvent}.
	 * @param source the {@code TestContext} associated with this event
	 * (must not be {@code null})
	 */
	/**
	 * 创建一个新的{@code  TestContextEvent}。 
	 *  
	 * @param 源与此事件关联的{@code  TestContext}（一定不能为{@code  null}）
	 */
	public TestContextEvent(TestContext source) {
		super(source);
	}

	/**
	 * Get the {@link TestContext} associated with this event.
	 * @return the {@code TestContext} associated with this event (never {@code null})
	 * @see #getTestContext()
	 */
	/**
	 * 获取与此事件关联的{@link  TestContext}。 
	 *  
	 * @return 与此事件关联的{@code  TestContext}（从不{@code  null}）
	 * @see  #getTestContext（）
	 */
	@Override
	public final TestContext getSource() {
		return (TestContext) super.getSource();
	}

	/**
	 * Alias for {@link #getSource()}.
	 * <p>This method may be favored over {@code getSource()} &mdash; for example,
	 * to improve readability in SpEL expressions for event processing
	 * {@linkplain org.springframework.context.event.EventListener#condition conditions}.
	 * @return the {@code TestContext} associated with this event (never {@code null})
	 * @see #getSource()
	 */
	/**
	 * {@link  #getSource（）}的别名。 
	 *  <p>此方法可能优于{@code  getSource（）} －例如，为了提高SpEL表达式在事件处理中的可读性{@link  plain org.springframework.context.event.EventListener＃condition条件} 。 
	 *  
	 * @return 与该事件关联的{@code  TestContext}（从不{@code  null}）
	 * @see  #getSource（）
	 */
	public final TestContext getTestContext() {
		return getSource();
	}

}
