/** Generated by english-annotation-buster, Powered by Google Translate.**/
/*
 * Copyright 2002-2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * 版权所有2002-2019的原始作者或作者。 
 * 根据Apache许可证2.0版（"许可证"）获得许可； 
 * 除非遵守许可，否则不得使用此文件。 
 * 您可以在https://www.apache.org/licenses/LICENSE-2.0上获得许可的副本。 
 * 除非适用法律要求或以书面形式同意，否则根据"许可"分发的软件将按"现状"分发，没有任何明示或暗示的保证或条件。 
 * 有关许可下特定的语言管理权限和限制，请参阅许可。 
 * 
 */

package org.springframework.messaging.rsocket;

import java.util.Map;
import java.util.function.BiConsumer;

import org.springframework.core.ParameterizedTypeReference;
import org.springframework.lang.Nullable;
import org.springframework.util.MimeType;

/**
 * Stores registrations of extractors for metadata entries.
 * Each metadata entry is decoded based on its {@code MimeType} and a name
 * is assigned to the decoded value.
 *
 * @author Rossen Stoyanchev
 * @author Brian Clozel
 * @since 5.2
 * @see MetadataExtractor
 */
/**
 * 存储元数据条目提取器的注册。 
 * 每个元数据条目均基于其{@code  MimeType}进行解码，并为解码后的值分配名称。 
 *  @author 罗森·斯托扬切夫（Rossen Stoyanchev）@author 布莱恩·克洛泽尔​​（Brian Clozel）@从5.2起
 * @see  MetadataExtractor
 */
public interface MetadataExtractorRegistry {

	/**
	 * Decode metadata entries with the given {@link MimeType} to the specified
	 * target class, and store the decoded value in the output map under the
	 * given name.
	 * @param mimeType the mime type of metadata entries to extract
	 * @param targetType the target value type to decode to
	 * @param name assign a name for the decoded value; if not provided, then
	 * the mime type is used as the key
	 */
	/**
	 * 将具有给定{@link  MimeType}的元数据条目解码为指定的目标类，并将解码后的值以给定名称存储在输出映射中。 
	 *  
	 * @param  mimeType要提取的元数据条目的mime类型
	 * @param  targetType要解码为的目标值类型
	 * @param  name为解码值指定名称； 
	 * 如果未提供，则将mime类型用作密钥
	 */
	default void metadataToExtract(MimeType mimeType, Class<?> targetType, @Nullable String name) {
		String key = name != null ? name : mimeType.toString();
		metadataToExtract(mimeType, targetType, (value, map) -> map.put(key, value));
	}

	/**
	 * Variant of {@link #metadataToExtract(MimeType, Class, String)} that accepts
	 * {@link ParameterizedTypeReference} instead of {@link Class} for
	 * specifying a target type with generic parameters.
	 * @param mimeType the mime type of metadata entries to extract
	 * @param targetType the target value type to decode to
	 */
	/**
	 * {@link  #metadataToExtract（MimeType，Class，String）}的变体，它接受{@link  ParameterizedTypeReference}而不是{@link  Class}来指定具有通用参数的目标类型。 
	 *  
	 * @param  mimeType要提取的元数据条目的mime类型
	 * @param  targetType要解码为的目标值类型
	 */
	default void metadataToExtract(
			MimeType mimeType, ParameterizedTypeReference<?> targetType, @Nullable String name) {

		String key = name != null ? name : mimeType.toString();
		metadataToExtract(mimeType, targetType, (value, map) -> map.put(key, value));
	}

	/**
	 * Variant of {@link #metadataToExtract(MimeType, Class, String)} that allows
	 * custom logic to be used to map the decoded value to any number of values
	 * in the output map.
	 * @param mimeType the mime type of metadata entries to extract
	 * @param targetType the target value type to decode to
	 * @param mapper custom logic to add the decoded value to the output map
	 * @param <T> the target value type
	 */
	/**
	 * {@link  #metadataToExtract（MimeType，Class，String）}的变体，该变体允许使用自定义逻辑将解码后的值映射到输出映射中的任意数量的值。 
	 *  
	 * @param  mimeType元数据条目的mime类型以提取
	 * @param  targetType目标值类型以解码为
	 * @param 映射器自定义逻辑，以将解码后的值添加到输出映射
	 * @param  <T>目标值类型
	 */
	<T> void metadataToExtract(
			MimeType mimeType, Class<T> targetType, BiConsumer<T, Map<String, Object>> mapper);

	/**
	 * Variant of {@link #metadataToExtract(MimeType, Class, BiConsumer)} that
	 * accepts {@link ParameterizedTypeReference} instead of {@link Class} for
	 * specifying a target type with generic parameters.
	 * @param mimeType the mime type of metadata entries to extract
	 * @param type the target value type to decode to
	 * @param mapper custom logic to add the decoded value to the output map
	 * @param <T> the target value type
	 */
	/**
	 * {@link  #metadataToExtract（MimeType，Class，BiConsumer）}的变体，它接受{@link  ParameterizedTypeReference}而不是{@link  Class}来指定具有通用参数的目标类型。 
	 *  
	 * @param  mime键入要提取的元数据条目的mime类型
	 * @param 键入要解码为
	 * @param 的映射器自定义逻辑的目标值类型，以将解码后的值添加到输出映射
	 * @param  <T>目标值类型
	 */
	<T> void metadataToExtract(
			MimeType mimeType, ParameterizedTypeReference<T> type, BiConsumer<T, Map<String, Object>> mapper);

}
