/** Generated by english-annotation-buster, Powered by Google Translate.**/
/**
 * Package providing integration of <a href="https://java.sun.com/webservices/jaxb/">JAXB</a>
 * with Spring's O/X Mapping support.
 */
/**
 * 该软件包提供了<a href="https://java.sun.com/webservices/jaxb/"> JAXB </a>与Spring的O / X映射支持的集成。 
 * 
 */
@NonNullApi
@NonNullFields
package org.springframework.oxm.jaxb;

import org.springframework.lang.NonNullApi;
import org.springframework.lang.NonNullFields;
