/** Generated by english-annotation-buster, Powered by Google Translate.**/
/**
 * Load-time weaving support for a Spring application context, building on Spring's
 * {@link org.springframework.instrument.classloading.LoadTimeWeaver} abstraction.
 */
/**
 * 对Spring应用程序上下文的加载时编织支持，基于Spring的{@link  org.springframework.instrument.classloading.LoadTimeWeaver}抽象。 
 * 
 */
@NonNullApi
@NonNullFields
package org.springframework.context.weaving;

import org.springframework.lang.NonNullApi;
import org.springframework.lang.NonNullFields;
