/** Generated by english-annotation-buster, Powered by Google Translate.**/
/*
 * Copyright 2002-2018 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/**
 * 版权所有2002-2018的原始作者。 
 * 根据Apache许可证2.0版（"许可证"）获得许可； 
 * 除非遵守许可，否则不得使用此文件。 
 * 您可以在https://www.apache.org/licenses/LICENSE-2.0上获得许可的副本。 
 * 除非适用法律要求或以书面形式同意，否则根据"许可"分发的软件将按"现状"分发，没有任何明示或暗示的保证或条件。 
 * 有关许可下特定的语言管理权限和限制，请参阅许可。 
 * 
 */

package org.springframework.http;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import org.springframework.core.log.LogDelegateFactory;

/**
 * Holds the shared logger named "org.springframework.web.HttpLogging" for HTTP
 * related logging when "org.springframework.http" is not enabled but
 * "org.springframework.web" is.
 *
 * <p>That means "org.springframework.web" enables all web logging including
 * from lower level packages such as "org.springframework.http" and modules
 * such as codecs from {@literal "spring-core"} when those are wrapped with
 * {@link org.springframework.http.codec.EncoderHttpMessageWriter EncoderHttpMessageWriter} or
 * {@link org.springframework.http.codec.DecoderHttpMessageReader DecoderHttpMessageReader}.
 *
 * <p>To see logging from the primary class loggers simply enable logging for
 * "org.springframework.http" and "org.springframework.codec".
 *
 * @author Rossen Stoyanchev
 * @since 5.1
 * @see LogDelegateFactory
 */
/**
 * 当未启用"org.springframework.http"但启用"org.springframework.web"时，保存名为"org.springframework.web.HttpLogging"的共享记录器以进行与HTTP相关的日志记录。 
 *  <p>这意味着"org.springframework.web"启用了所有Web日志记录，包括来自较低级软件包（例如"org.springframework.http"）和模块（例如来自{@literal"spring-core"}的编解码器）的记录{@link  org.springframework.http.codec.EncoderHttpMessageWriter EncoderHttpMessageWriter}或{@link  org.springframework.http.codec.DecoderHttpMessageReader DecoderHttpMessageReader}。 
 *  <p>要查看来自主类的日志记录器，只需启用"org.springframework.http"和"org.springframework.codec"的日志记录即可。 
 *  @author  Rossen Stoyanchev @从5.1开始
 * @see  LogDelegateFactory
 */
public abstract class HttpLogging {

	private static final Log fallbackLogger =
			LogFactory.getLog("org.springframework.web." + HttpLogging.class.getSimpleName());


	/**
	 * Create a primary logger for the given class and wrap it with a composite
	 * that delegates to it or to the fallback logger
	 * "org.springframework.web.HttpLogging", if the primary is not enabled.
	 * @param primaryLoggerClass the class for the name of the primary logger
	 * @return the resulting composite logger
	 */
	/**
	 * 为给定的类创建一个主记录器，并用一个委托给它的组合或一个后备记录器"org.springframework.web.HttpLogging"（如果未启用主记录器）将其包装。 
	 *  
	 * @param  primaryLoggerClass主记录器名称的类
	 * @return 生成的复合记录器
	 */
	public static Log forLogName(Class<?> primaryLoggerClass) {
		Log primaryLogger = LogFactory.getLog(primaryLoggerClass);
		return forLog(primaryLogger);
	}

	/**
	 * Wrap the given primary logger with a composite logger that delegates to
	 * it or to the fallback logger "org.springframework.web.HttpLogging",
	 * if the primary is not enabled.
	 * @param primaryLogger the primary logger to use
	 * @return the resulting composite logger
	 */
	/**
	 * 如果未启用主记录器，则将给定的主记录器与委派给该主记录器或后备记录器"org.springframework.web.HttpLogging"的复合记录器进行包装。 
	 *  
	 * @param  primaryLogger主记录器使用
	 * @return 生成的复合记录器
	 */
	public static Log forLog(Log primaryLogger) {
		return LogDelegateFactory.getCompositeLog(primaryLogger, fallbackLogger);
	}

}
